### ISSUE TITLE
How to use slcan0 for can data transmission

### ISSUE THREAD

**Issue by pioneerAlone** [PonomarevDA/tools#9]
Hello ,

I tried to use the script here to create a slcan0, but I don’t quite understand how to use it. Can I use it directly for in-system testing without linking to any physical CAN sniffer?

#slcan0 created below:
slcan0: flags=193<UP,RUNNING,NOARP>  mtu 72
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 1000  (UNSPEC)
        RX packets 349  bytes 2758 (2.7 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 349  bytes 2758 (2.7 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

#!/bin/bash
export UAVCAN__CAN__IFACE='socketcan:slcan0'
export UAVCAN__CAN__MTU=8
export UAVCAN__NODE__ID=$1  # Pick an unoccupied node-ID automatically for this shell session.
echo "Auto-selected node-ID for this session: $UAVCAN__NODE__ID"

**Comment by PonomarevDA** [comment]
> Can I use it directly for in-system testing without linking to any physical CAN sniffer?

I assume you are trying to test a Cyphal/CAN application without a real hardware with Yakut or Yukon.

Yes, this is possible.

For instance, all RaccoonLab Cyphal nodes can be built both as a binary for stm32 and as an executable to run in SITL mode (this is one of the ways how we test the software). Although the software is not open, so I can't shown you a real example right now.

I'm planning to add a SITL mode for [mini v2 example](https://github.com/RaccoonlabDev/mini_v2_node), because it's quite common that a user doesn't have a real hardware. But I see that this can only happen next year.

For general running cyphal nodes and testing them with yakut/yukon I would recommend checking the Cyphal repositories/forum/tutorials. It might be useful to open an issue there or create a related topic on Cyphal forum if something is not clear.

Anyway, I've updated the docs here and the [cyphal/init.sh](https://github.com/PonomarevDA/tools/blob/main/cyphal/init.sh) script. I've improved the workflows to make sure that my scripts work not only on my environment. Please, check [README.md](https://github.com/PonomarevDA/tools#cyphalcan) and [cyphal/README.md](https://github.com/PonomarevDA/tools/tree/main/cyphal#1-cyphalinitsh) for details and workflows for example if something is not clear. Write here if it helps you.

**Comment by pioneerAlone** [comment]
Thanks for your clarification,
Will have a try.
